### ISSUE TITLE
Not pulling SPF records for yahoo.com

### ISSUE THREAD

**Issue by sysfu** [toddfries/spf2cidr#1]
When the spf2cidr script is run with the -v (verbose) option and only 'yahoo.com' in the spf-domains file, this is all the output that it yields.

```
#
#     
#
#
#     yahoo.com
#
# v=spf1 (yahoo.com)
# redirect=_spf.mail.yahoo.com (yahoo.com)
#
#     _spf.mail.yahoo.com
#
# v=spf1 (_spf.mail.yahoo.com)
# ptr:yahoo.com (_spf.mail.yahoo.com)
# ptr:yahoo.net (_spf.mail.yahoo.com)
# ?all -> all (_spf.mail.yahoo.com)
```

Every other domain I've tested works as expected so far.

**Comment by sysfu** [comment]
I did some more research and apparently [Yahoo does in fact publish an SPF record](http://serverfault.com/a/676016), it just doesn't include any IP addresses or networks in CIDR format. 

All you're going to get is the ptr:yahoo.com/net records and that's it, which does not help with spamd.

**Comment by captvic** [comment]
Did not want to start a new issue because it is similar.
AOL is doing the same thing for aol.com, using the ptr option for spf records.
 ptr:mx.aol.com

As with Yahoo, this does not yield any IP address.
They do list their servers at:
https://postmaster.aol.com/mail-servers
which I created a list and added to my whitelist.txt

You can close this issue. 
Just wanted to share that aol.com was not creating cidr info.
Thanks for the script.
